### ISSUE TITLE
Running NYX on Benchmark with from the paper

### ISSUE THREAD

**Issue by 428studios** [Troublor/Nyx#3]
I am trying to redo the benchmark mentioned in the paper by running NYX on the benchmark with 513 attacks. However, I am encountering some issues during execution. Below is the error code I received on some contracts:

```python
python nyx/main.py ./benchmark/contracts/SwapRouter-0xE592427A0AEce92De3Edee1F18E0157C05861564 --solver-timeout 900
2024-06-25T12:43:57.381603 [info     ] Command-line arguments         focus=[] log_file=None name=Contracts output=result.json repos=['./benchmark/contracts/SwapRouter-0xE592427A0AEce92De3Edee1F18E0157C05861564']                                                                                            
2024-06-25T12:43:57.381775 [info     ] Analysis configuration         function_timeout=infs pair_timeout=infs solver_timeout=900.00s
2024-06-25T12:43:57.388867 [info     ] Analysis started               group=Contracts
2024-06-25T12:43:57.388982 [info     ] Phase 0 analysis started       group=Contracts
2024-06-25T12:43:57.389057 [info     ] Compiling and analyzing contracts using Slither... group=Contracts path=benchmark/contracts/SwapRouter-0xE592427A0AEce92De3Edee1F18E0157C05861564 phase=0 repo=                                                                                                          
2024-06-25T12:43:57.390290 [info     ] '/home/kali/.solc-select/artifacts/solc-0.7.6/solc-0.7.6 --version' running
2024-06-25T12:43:57.392611 [info     ] '/home/kali/.solc-select/artifacts/solc-0.7.6/solc-0.7.6 contracts/SwapRouter.sol --combined-json abi,ast,bin,bin-runtime,srcmap,srcmap-runtime,userdoc,devdoc,hashes,compact-format --optimize --allow-paths .,/home/kali/Nyx/contracts' running
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.11/site-packages/crytic_compile/platform/solc.py", line 582, in _run_solc
    ret: Dict = json.loads(stdout)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Nyx/nyx/main.py", line 214, in <module>
    analyze_one(args)
  File "/home/kali/Nyx/nyx/main.py", line 84, in analyze_one
    output = analyze_single(group, observer, config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Nyx/nyx/analyze/__init__.py", line 38, in analyze_single
    _ = repo.slither
        ^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Nyx/nyx/galaxy/ContractRepo.py", line 136, in slither
    self._slither = Slither(self.crytic_compile)
                            ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Nyx/nyx/galaxy/ContractRepo.py", line 122, in crytic_compile
    self._crytic_compile = CryticCompile(
                           ^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 211, in __init__
    self._compile(**kwargs)
  File "/home/kali/.local/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 633, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/kali/.local/lib/python3.11/site-packages/crytic_compile/platform/solc.py", line 151, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/crytic_compile/platform/solc.py", line 280, in _get_targets_json
    return _run_solc(
           ^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/crytic_compile/platform/solc.py", line 586, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Source "src/@uniswap/v3-core/contracts/libraries/SafeCast.sol" not found: File not found.
 --> contracts/SwapRouter.sol:5:1:
  |
5 | import "src/@uniswap/v3-core/contracts/libraries/SafeCast.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "src/@uniswap/v3-core/contracts/libraries/TickMath.sol" not found: File not found.
 --> contracts/SwapRouter.sol:6:1:
  |
6 | import "src/@uniswap/v3-core/contracts/libraries/TickMath.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "src/@uniswap/v3-core/contracts/interfaces/IUniswapV3Pool.sol" not found: File not found.
 --> contracts/SwapRouter.sol:7:1:
  |
7 | import "src/@uniswap/v3-core/contracts/interfaces/IUniswapV3Pool.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "src/@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File not found.
 --> contracts/base/PeripheryPaymentsWithFee.sol:4:1:
  |
4 | import "src/@openzeppelin/contracts/token/ERC20/IERC20.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "src/@uniswap/v3-core/contracts/libraries/LowGasSafeMath.sol" not found: File not found.
 --> contracts/base/PeripheryPaymentsWithFee.sol:5:1:
  |
5 | import "src/@uniswap/v3-core/contracts/libraries/LowGasSafeMath.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "src/@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File not found.
 --> contracts/base/SelfPermit.sol:4:1:
  |
4 | import "src/@openzeppelin/contracts/token/ERC20/IERC20.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "src/@openzeppelin/contracts/drafts/IERC20Permit.sol" not found: File not found.
 --> contracts/base/SelfPermit.sol:5:1:
  |
5 | import "src/@openzeppelin/contracts/drafts/IERC20Permit.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "src/@uniswap/v3-core/contracts/interfaces/callback/IUniswapV3SwapCallback.sol" not found: File not found.
 --> contracts/interfaces/ISwapRouter.sol:5:1:
  |
5 | import "src/@uniswap/v3-core/contracts/interfaces/callback/IUniswapV3SwapCallback.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "src/@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File not found.
 --> contracts/interfaces/external/IWETH9.sol:4:1:
  |
4 | import "src/@openzeppelin/contracts/token/ERC20/IERC20.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "src/@uniswap/v3-core/contracts/interfaces/IUniswapV3Pool.sol" not found: File not found.
 --> contracts/libraries/CallbackValidation.sol:4:1:
  |
4 | import "src/@uniswap/v3-core/contracts/interfaces/IUniswapV3Pool.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "src/@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File not found.
 --> contracts/base/PeripheryPayments.sol:4:1:
  |
4 | import "src/@openzeppelin/contracts/token/ERC20/IERC20.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "src/@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File not found.
 --> contracts/libraries/TransferHelper.sol:4:1:
  |
4 | import "src/@openzeppelin/contracts/token/ERC20/IERC20.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

``` 

Steps to Reproduce

    1.Clone the repository and navigate to the benchmark directory.
    2.Set up the environment as described in the documentation.
    3.Run NYX on the benchmark using the following command:
```python
python nyx/main.py ./benchmark/contracts/SwapRouter-0xE592427A0AEce92De3Edee1F18E0157C05861564
``` 

Additional Information:
Error: File not found even though the files are there. 

I would appreciate any help or guidance on resolving this issue. Thank you!

**Comment by Nicole4Fox** [comment]
@428studios btw how did you generate the metadata files to analyse with nyx?
